export {default as Login} from './auth/Login'
export {default as Register} from './auth/Register'
export {default as ForgetPassword} from './auth/ForgetPassword'
export {default as Profile} from './auth/Profile'
export {default as Home} from './Home'